
driver.find_element(By.XPATH,'//*[@id="content"]/h1').click()
time.sleep(2)
yash=Select(driver.find_element(By.NAME,'subject'))
yash.select_by_index(44)
time.sleep(2)
yash=Select(driver.find_element(By.NAME,'bookseries'))
yash.select_by_index(26)
time.sleep(2)
yash=Select(driver.find_element(By.NAME,'classid'))
yash.select_by_index(5)
time.sleep(2)
driver.find_element(By.NAME,'solution').send_keys("C:\\Users\khape\\Downloads\\JAI BHOLE ENTERPRIZES (1).pdf")
time.sleep(2)
driver.find_element(By.NAME,'_save').click()
time.sleep(2)





time.sleep(2)time.sleep(2)



driver.find_element(By.XPATH,'//*[@id="content-main"]/div[3]/table/tbody/tr[6]/th/a').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[3]/table/tbody/tr[6]/td/a').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="content"]/h1').click()
time.sleep(2)
driver.find_element(By.NAME,'suggestion').send_keys('Shape around plot development. Some book authors like to end each chapter with a cliffhanger, ')
time.sleep(2)
driver.find_element(By.NAME,'_save').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[3]/table/tbody/tr[5]/th/a').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[3]/table/tbody/tr[5]/td/a').click()
time.sleep(2)
driver.find_element(By.NAME,'state').send_keys('MAHARASTRA')
time.sleep(2)
driver.find_element(By.NAME,'_save').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[3]/table/tbody/tr[4]/th/a').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[3]/table/tbody/tr[4]/td/a').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="content"]/h1').click()
time.sleep(2)
yash=Select(driver.find_element(By.NAME,'subject'))
yash.select_by_index(44)
time.sleep(2)
yash=Select(driver.find_element(By.NAME,'bookseries'))
yash.select_by_index(26)
time.sleep(2)
yash=Select(driver.find_element(By.NAME,'classid'))
yash.select_by_index(5)
time.sleep(2)
driver.find_element(By.NAME,'solution').send_keys("C:\\Users\khape\\Downloads\\JAI BHOLE ENTERPRIZES (1).pdf")
time.sleep(2)
driver.find_element(By.NAME,'_save').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[3]/table/tbody/tr[5]/th/a').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[3]/table/tbody/tr[5]/td/a').click()
time.sleep(2)
