import time
from selenium.webdriver.support.ui import Select

from selenium import webdriver

from selenium.webdriver.common.by import By

driver=webdriver.Chrome(executable_path="C:\\Users\khape\Downloads\chromedriver_win32 (2)\chrome"
                                        "driver.exe")

driver.get("http://mitintech.com/admin/")
time.sleep(2)
driver.find_element(By.NAME,'username').send_keys('YASHKHAPEKAR')
time.sleep(2)
driver.find_element(By.NAME,'password').send_keys('YASH@160620')
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="login-form"]/div[3]/input').click()
time.sleep(2)

driver.find_element(By.XPATH,'//*[@id="content-main"]/div[2]/table/tbody/tr[4]/th/a').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="content"]/h1')
time.sleep(3)

driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[2]/table/tbody/tr[4]/td/a').click()
time.sleep(3)
driver.find_element(By.XPATH,'//*[@id="content"]/h1')
time.sleep(3)
driver.find_element(By.NAME,'name').send_keys('GEOGRAPHY')
time.sleep(2)
driver.find_element(By.NAME,'description').send_keys('THIS IS MY FVT SUBJECT')
time.sleep(2)
driver.find_element(By.NAME,'_save').click()
time.sleep(2)
driver.find_element(By.NAME,'_addanother').click()
time.sleep(2)
driver.find_element(By.NAME,'_continue').click()
time.sleep(2)
driver.find_element(By.LINK_TEXT,'Book Series').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[2]/table/tbody/tr[1]/td/a').click()
time.sleep(1)
driver.find_element(By.XPATH,'//*[@id="content"]/h1').click()
time.sleep(2)
selsub=Select(driver.find_element(By.XPATH,'//*[@id="id_subject"]'))
selsub.select_by_index(28)
time.sleep(2)
driver.find_element(By.NAME,'name').send_keys('YASH KHAPEKAR')
time.sleep(3)
driver.find_element(By.NAME,'_save').click()
time.sleep(1)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[2]/table/tbody/tr[3]/th/a').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[2]/table/tbody/tr[3]/td/a').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="content"]/h1').click()
time.sleep(2)
driver.find_element(By.NAME,'name').send_keys(12)
time.sleep(2)
driver.find_element(By.NAME,'_save').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[2]/table/tbody/tr[2]/th/a').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[2]/table/tbody/tr[2]/td/a').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="content"]/h1').click()
time.sleep(2)
driver.find_element(By.NAME,'name').send_keys('YASH KHAPEKAR')
time.sleep(2)
selsub=Select(driver.find_element(By.XPATH,'//*[@id="id_subject"]'))
selsub.select_by_index(28)
time.sleep(3)
selsub=Select(driver.find_element(By.XPATH,'//*[@id="id_bookseries"]'))
selsub.select_by_index(25)
time.sleep(3)
selsub=Select(driver.find_element(By.XPATH,'//*[@id="id_classid"]'))
selsub.select_by_index(22)
time.sleep(3)
driver.find_element(By.NAME,'_save').click()
time.sleep(3)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[3]/table/tbody/tr[3]/th/a').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[3]/table/tbody/tr[3]/td/a').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="content"]/h1').click()
time.sleep(3)
selsub=Select(driver.find_element(By.XPATH,'//*[@id="id_subject"]'))
selsub.select_by_index(28)
time.sleep(2)
selsub=Select(driver.find_element(By.XPATH,'//*[@id="id_bookseries"]'))
selsub.select_by_index(25)
time.sleep(2)
selsub=Select(driver.find_element(By.NAME,'classid'))
selsub.select_by_index(22)
time.sleep(2)
driver.find_element (By.XPATH,'//*[@id="id_lesson"]').send_keys("C:\\Users\khape\\Downloads\\JAI BHOLE ENTERPRIZES (1).pdf")
time.sleep(2)
driver.find_element(By.NAME,'_save').click()
time.sleep(3)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[3]/table/tbody/tr[4]/th/a').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[3]/table/tbody/tr[4]/td/a').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="content"]/h1')
time.sleep(2)
selsub=Select(driver.find_element(By.NAME,'subject'))
selsub.select_by_index(28)
time.sleep(2)
selsub=Select(driver.find_element(By.NAME,'bookseries'))
selsub.select_by_index(24)
time.sleep(2)
selsub=Select(driver.find_element(By.NAME,'classid'))
selsub.select_by_index(23)
time.sleep(2)
driver.find_element (By.XPATH,'//*[@id="id_solution"]').send_keys("C:\\Users\khape\\Downloads\\JAI BHOLE ENTERPRIZES (1).pdf")
time.sleep(2)
driver.find_element(By.NAME,'_save').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[3]/table/tbody/tr[9]/th/a').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[3]/table/tbody/tr[9]/td/a').click()
time.sleep(2)
driver.find_element (By.XPATH,'//*[@id="id_worksheet1"]').send_keys("C:\\Users\khape\\Downloads\\JAI BHOLE ENTERPRIZES (1).pdf")
time.sleep(2)
driver.find_element (By.XPATH,'//*[@id="id_worksheet2"]').send_keys("C:\\Users\khape\\Downloads\\JAI BHOLE ENTERPRIZES (1).pdf")
time.sleep(2)
selsub=Select(driver.find_element(By.NAME,'subject'))
selsub.select_by_index(28)
time.sleep(2)
selsub=Select(driver.find_element(By.NAME,'bookseries'))
selsub.select_by_index(24)
time.sleep(2)
selsub=Select(driver.find_element(By.NAME,'classid'))
selsub.select_by_index(23)
time.sleep(2)
selsub=Select(driver.find_element(By.NAME,'chapter'))
selsub.select_by_index(18)
time.sleep(2)
driver.find_element(By.NAME,'_save').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[3]/table/tbody/tr[8]/th/a').click()

time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[3]/table/tbody/tr[8]/td/a').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="content"]/h1').click()
time.sleep(2)
selsub=Select(driver.find_element(By.NAME,'user'))
selsub.select_by_index(4)
time.sleep(2)
driver.find_element(By.NAME,'schools').send_keys("SINDHI HINDI HIGH SCHOOL")
time.sleep(2)
selsub=Select(driver.find_element(By.NAME,'subject'))
selsub.select_by_index(29)
time.sleep(2)
selsub=Select(driver.find_element(By.NAME,'bookseries'))
selsub.select_by_index(26)
time.sleep(2)
selsub=Select(driver.find_element(By.NAME,'state'))
selsub.select_by_index(1)
time.sleep(2)
selsub=Select(driver.find_element(By.NAME,'city'))
selsub.select_by_index(1)
time.sleep(1)
driver.find_element(By.NAME,'mobile').send_keys("7420921250")
time.sleep(10)
driver.find_element(By.NAME,'status').click()
time.sleep(3)
driver.find_element(By.NAME,'_save').click()
time.sleep(3)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[3]/table/tbody/tr[7]/th/a').click()
time.sleep(3)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[3]/table/tbody/tr[7]/td/a').click()
time.sleep(3)
driver.find_element(By.XPATH,'//*[@id="content"]/h1').click()
time.sleep(3)
selsub=Select(driver.find_element(By.NAME,'subject'))
selsub.select_by_index(29)
time.sleep(2)
selsub=Select(driver.find_element(By.NAME,'bookseries'))
selsub.select_by_index(24)
time.sleep(2)
selsub=Select(driver.find_element(By.NAME,'classid'))
selsub.select_by_index(23)
time.sleep(2)
driver.find_element (By.XPATH,'//*[@id="id_viewbook"]').send_keys("C:\\Users\khape\\Downloads\\JAI BHOLE ENTERPRIZES (1).pdf")
time.sleep(2)
driver.find_element(By.NAME,'_save').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[3]/table/tbody/tr[6]/th/a').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[3]/table/tbody/tr[6]/td/a').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="content"]/h1').click()
time.sleep(2)
driver.find_element(By.NAME,'suggestion').send_keys(". Shape around plot development. Some book authors like to end each chapter with a cliffhanger, whether that’s an unresolved conflict between characters, a new crucial piece of information, or an actual cliff. Anything to keep the reader engaged in what comes next.")
time.sleep(3)
driver.find_element(By.NAME,'_save').click()
time.sleep(3)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[3]/table/tbody/tr[2]/th/a').click()
time.sleep(3)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[3]/table/tbody/tr[2]/td/a').click()
time.sleep(3)
driver.find_element(By.XPATH,'//*[@id="content"]/h1').click()
time.sleep(3)
driver.find_element(By.NAME,'city').send_keys("NAGPUR")
time.sleep(3)
selsub=Select(driver.find_element(By.NAME,'state'))
selsub.select_by_index(1)
time.sleep(2)
driver.find_element(By.NAME,'_save').click()
time.sleep(3)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[3]/table/tbody/tr[5]/th/a').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[3]/table/tbody/tr[5]/td/a').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="content"]/h1').click()
time.sleep(2)
driver.find_element(By.NAME,'state').send_keys("MAHARASHTRA")
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[3]/table/tbody/tr[1]/th/a').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[3]/table/tbody/tr[1]/td/a').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="content"]/h1').click()
time.sleep(2)
driver.find_element(By.NAME,'review').send_keys(
"This class was excellent--where have you been all my life")
time.sleep(2)
driver.find_element(By.NAME,'rating').send_keys(" *****")
time.sleep(2)
driver.find_element(By.NAME,'_save').click()
time.sleep(10)


























