import time
from selenium.webdriver.support.ui import Select

from selenium import webdriver

from selenium.webdriver.common.by import By

driver=webdriver.Chrome(executable_path="C:\\Users\khape\Downloads\chromedriver_win32 (2)\chromedriver.exe")

driver.get("http://mitintech.com/admin/")
time.sleep(2)
time.sleep(2)
driver.find_element(By.NAME,'username').send_keys('YASHKHAPEKAR')
time.sleep(2)
driver.find_element(By.NAME,'password').send_keys('YASH@160620')
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="login-form"]/div[3]/input').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="content-main"]/div[2]/table/tbody/tr[4]/th/a').click()
time.sleep(3)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[2]/table/tbody/tr[4]/td/a').click()
time.sleep(3)
driver.find_element(By.XPATH,'//*[@id="content"]/h1').click()
time.sleep(3)
driver.find_element(By.NAME,'name').send_keys('HISTORY')
time.sleep(2)
driver.find_element(By.NAME,'description').send_keys('HISTORY IS MY FVT SUBJECT')
time.sleep(2)
driver.find_element(By.NAME,'_save').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[2]/table/tbody/tr[1]/th/a').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[2]/table/tbody/tr[1]/td/a').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="content"]/h1').click()
time.sleep(2)
yash=Select(driver.find_element(By.NAME,'subject'))
yash.select_by_index(44)
time.sleep(2)
driver.find_element(By.NAME,'name').send_keys('THIS IS MY FVT SUBJECT')
time.sleep(2)
driver.find_element(By.NAME,'_save').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[2]/table/tbody/tr[3]/th/a').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[2]/table/tbody/tr[3]/td/a').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="content"]/h1').click()
time.sleep(2)
driver.find_element(By.NAME,'name').send_keys('12th')
time.sleep(2)
driver.find_element(By.NAME,'_save').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[2]/table/tbody/tr[2]/th/a').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="nav-sidebar"]/div[2]/table/tbody/tr[2]/td/a').click()
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id="content"]/h1').click()
time.sleep(2)
driver.find_element(By.NAME,'name').send_keys('YASH KHAPEKAR')
time.sleep(2)
yash=Select(driver.find_element(By.NAME,'subject'))
yash.select_by_index(44)
time.sleep(2)
yash=Select(driver.find_element(By.NAME,'bookseries'))
yash.select_by_index(44)
time.sleep(2)
yash=Select(driver.find_element(By.NAME,'classid'))
yash.select_by_index(5)
time.sleep(2)
driver.find_element(By.NAME,'_save').click()
time.sleep(12)



